import Foundation

enum AccessL10nKey {
    static let brandReguerta = "common.brand.reguerta"

    static let membersRolesTitle = "access.members_roles.title"
    static let signedOutHint = "access.signed_out.hint"
    static let authenticationCardTitle = "access.card.authentication"
    static let emailLabel = "common.input.email.label"
    static let passwordLabel = "common.input.password.label"
    static let inputPlaceholderTapToType = "common.input.tap_to_type"
    static let authUidLabel = "access.input.auth_uid.label"
    static let signingIn = "access.action.signing_in"
    static let signIn = "access.action.sign_in"
    static let signOut = "access.action.sign_out"
    static let dismissMessage = "access.action.dismiss_message"
    static let splashLoading = "auth_shell.splash.loading"
    static let startupUpdateForcedTitle = "startup.update.forced.title"
    static let startupUpdateOptionalTitle = "startup.update.optional.title"
    static let startupUpdateMessage = "startup.update.message"
    static let startupUpdateActionUpdate = "startup.update.action.update"
    static let startupUpdateActionLater = "startup.update.action.later"
    static let commonAccept = "common.action.accept"
    static let commonBack = "common.action.back"
    static let commonClear = "common.action.clear"
    static let commonShowPassword = "common.action.show_password"
    static let commonHidePassword = "common.action.hide_password"

    static let unauthorized = "auth_error.member.unauthorized"
    static let unauthorizedDialogTitle = "auth_dialog.member.unauthorized.title"
    static let unauthorizedDialogMessage = "auth_dialog.member.unauthorized.message"
    static let unauthorizedDialogAction = "auth_dialog.member.unauthorized.action"
    static let unauthorizedExplanation = "auth_info.member.unauthorized_explanation"
    static let signedInEmail = "access.signed_in_email"
    static let restrictedModeInfo = "auth_info.member.restricted_mode"
    static let unauthorizedContactAdmin = "auth_info.member.contact_admin"
    static let reason = "common.reason"

    static let welcomeTitlePrefix = "welcome.title.prefix"
    static let welcomeTitleBrand = "welcome.title.brand"
    static let welcomeSubtitle = "welcome.subtitle"
    static let welcomeCtaEnter = "welcome.cta.enter"
    static let welcomeNotRegistered = "welcome.not_registered"
    static let welcomeLinkRegister = "welcome.link.register"
    static let loginTitle = "login.title"
    static let loginLinkRegister = "login.link.register"
    static let loginLinkForgotPassword = "login.link.forgot_password"
    static let registerTitle = "register.title"
    static let registerSubtitle = "register.subtitle"
    static let registerRepeatPasswordLabel = "register.repeat_password.label"
    static let registerActionCreateAccount = "register.action.create_account"
    static let registerActionCreating = "register.action.creating"
    static let recoverTitle = "recover.title"
    static let recoverSubtitle = "recover.subtitle"
    static let recoverActionSendEmail = "recover.action.send_email"
    static let recoverActionSending = "recover.action.sending"
    static let recoverSuccessDialogTitle = "recover.success.dialog.title"
    static let recoverSuccessDialogMessage = "recover.success.dialog.message"
    static let sessionExpiredTitle = "session.expired.title"
    static let sessionExpiredMessage = "session.expired.message"
    static let sessionExpiredAction = "session.expired.action"

    static let homeTitle = "home.title"
    static let homeWelcome = "home.welcome"
    static let homeShellMenu = "home.shell.menu"
    static let homeShellNotifications = "home.shell.notifications"
    static let homeShellProfilePlaceholder = "home.shell.profile_placeholder"
    static let homeShellSectionCommon = "home.shell.section.common"
    static let homeShellSectionProducer = "home.shell.section.producer"
    static let homeShellSectionAdmin = "home.shell.section.admin"
    static let homeShellActionProducts = "home.shell.action.products"
    static let homeShellActionReceivedOrders = "home.shell.action.received_orders"
    static let homeShellActionUsers = "home.shell.action.users"
    static let homeShellActionProfile = "home.shell.action.profile"
    static let homeShellActionSettings = "home.shell.action.settings"
    static let homeShellActionPublishNews = "home.shell.action.publish_news"
    static let homeShellActionAdminBroadcast = "home.shell.action.admin_broadcast"
    static let homeShellBadgeSoon = "home.shell.badge.soon"
    static let homeShellWeeklyTitle = "home.shell.weekly.title"
    static let homeShellWeeklyResponsible = "home.shell.weekly.responsible"
    static let homeShellWeeklySupport = "home.shell.weekly.support"
    static let homeShellWeeklyMainProducer = "home.shell.weekly.main_producer"
    static let homeShellWeeklyDelivery = "home.shell.weekly.delivery"
    static let homeShellWeeklyDeliveryDefault = "home.shell.weekly.delivery.default"
    static let homeShellWeeklyPending = "home.shell.weekly.pending"
    static let shiftsNextTitle = "shifts.next.title"
    static let shiftsNextSubtitle = "shifts.next.subtitle"
    static let shiftsNextDelivery = "shifts.next.delivery"
    static let shiftsNextMarket = "shifts.next.market"
    static let shiftsNextPending = "shifts.next.pending"
    static let shiftsViewAll = "shifts.view_all"
    static let shiftsListSubtitle = "shifts.list.subtitle"
    static let shiftsRefreshAction = "shifts.refresh.action"
    static let shiftsLoading = "shifts.loading"
    static let shiftsEmptyState = "shifts.empty_state"
    static let shiftsTypeDelivery = "shifts.type.delivery"
    static let shiftsTypeMarket = "shifts.type.market"
    static let shiftsStatusPlanned = "shifts.status.planned"
    static let shiftsStatusSwapPending = "shifts.status.swap_pending"
    static let shiftsStatusConfirmed = "shifts.status.confirmed"
    static let shiftsAssignedMembersFormat = "shifts.assigned_members.format"
    static let shiftsHelperFormat = "shifts.helper.format"
    static let homeShellNewsTitle = "home.shell.news.title"
    static let homeShellNewsIntro = "home.shell.news.intro"
    static let homeShellNewsItemOne = "home.shell.news.item_one"
    static let homeShellNewsItemTwo = "home.shell.news.item_two"
    static let homeShellVersion = "home.shell.version"
    static let homePlaceholderSubtitle = "home.placeholder.subtitle"
    static let homePlaceholderMyOrder = "home.placeholder.my_order"
    static let homePlaceholderMyOrders = "home.placeholder.my_orders"
    static let homePlaceholderShifts = "home.placeholder.shifts"
    static let homePlaceholderNotifications = "home.placeholder.notifications"
    static let homePlaceholderProfile = "home.placeholder.profile"
    static let homePlaceholderSettings = "home.placeholder.settings"
    static let homePlaceholderProducts = "home.placeholder.products"
    static let homePlaceholderReceivedOrders = "home.placeholder.received_orders"
    static let homePlaceholderUsers = "home.placeholder.users"
    static let homePlaceholderAdminBroadcast = "home.placeholder.admin_broadcast"

    static let roles = "common.roles"
    static let status = "common.status"
    static let statusActive = "common.status.active"
    static let statusInactive = "common.status.inactive"

    static let operationalModulesTitle = "operational_modules.title"
    static let myOrder = "operational_modules.my_order"
    static let myOrders = "operational_modules.my_orders"
    static let catalog = "operational_modules.catalog"
    static let shifts = "operational_modules.shifts"
    static let operationalModulesRestrictedUnauthorized = "operational_modules.restricted.unauthorized"
    static let myOrderFreshnessChecking = "operational_modules.my_order.freshness.checking"
    static let myOrderFreshnessErrorTitle = "operational_modules.my_order.freshness.error.title"
    static let myOrderFreshnessErrorMessage = "operational_modules.my_order.freshness.error.message"
    static let myOrderFreshnessRetry = "operational_modules.my_order.freshness.retry"

    static let adminManageMembersTitle = "admin.manage_members.title"
    static let adminManageMembersSubtitle = "admin.manage_members.subtitle"
    static let adminCreatePreAuthorizedTitle = "admin.create_pre_authorized_member.title"
    static let displayNameLabel = "admin.input.display_name.label"
    static let roleMember = "role.member"
    static let roleProducer = "role.producer"
    static let roleAdmin = "role.admin"
    static let roleActive = "role.active"
    static let createMember = "admin.action.create_member"
    static let authLinked = "member.auth_linked"
    static let yes = "common.yes"
    static let no = "common.no"
    static let revokeAdmin = "admin.action.revoke_admin"
    static let grantAdmin = "admin.action.grant_admin"
    static let deactivate = "admin.action.deactivate"
    static let activate = "admin.action.activate"

    static let feedbackEmailUidRequired = "feedback.email_uid_required"
    static let feedbackEmailRequired = "feedback.email_required"
    static let feedbackPasswordRequired = "feedback.password_required"
    static let feedbackEmailInvalid = "feedback.email_invalid"
    static let authErrorInvalidCredentials = "auth_error.invalid_credentials"
    static let authErrorUserNotFound = "auth_error.user_not_found"
    static let authErrorUserDisabled = "auth_error.user_disabled"
    static let authErrorEmailAlreadyInUse = "auth_error.email_already_in_use"
    static let authErrorWeakPassword = "auth_error.weak_password"
    static let authErrorTooManyRequests = "auth_error.too_many_requests"
    static let authErrorNetwork = "auth_error.network"
    static let authErrorUnknown = "auth_error.unknown"
    static let authInfoPasswordResetSent = "auth_info.password_reset_sent"
    static let feedbackPasswordRepeatRequired = "feedback.password_repeat_required"
    static let feedbackPasswordMismatch = "feedback.password_mismatch"
    static let feedbackOnlyAdminCreate = "feedback.only_admin_create"
    static let feedbackDisplayNameEmailRequired = "feedback.display_name_email_required"
    static let feedbackMemberExists = "feedback.member_exists"
    static let feedbackSelectRole = "feedback.select_role"
    static let feedbackOnlyAdminEditRoles = "feedback.only_admin_edit_roles"
    static let feedbackOnlyAdminToggleActive = "feedback.only_admin_toggle_active"
    static let feedbackOnlyAdminManageMembers = "feedback.only_admin_manage_members"
    static let feedbackCannotRemoveLastAdmin = "feedback.cannot_remove_last_admin"
    static let feedbackUnableSaveChanges = "feedback.unable_save_changes"
    static let feedbackShiftSwapNoCandidates = "feedback.shift_swap_no_candidates"
    static let feedbackOnlyAdminPublishNews = "feedback.only_admin_publish_news"
    static let feedbackOnlyAdminEditNews = "feedback.only_admin_edit_news"
    static let feedbackOnlyAdminDeleteNews = "feedback.only_admin_delete_news"
    static let feedbackNewsTitleBodyRequired = "feedback.news_title_body_required"
    static let feedbackNewsCreated = "feedback.news_created"
    static let feedbackNewsUpdated = "feedback.news_updated"
    static let feedbackNewsDeleted = "feedback.news_deleted"
    static let feedbackNewsDeleteFailed = "feedback.news_delete_failed"
    static let feedbackOnlyAdminSendNotification = "feedback.only_admin_send_notification"
    static let feedbackNotificationTitleBodyRequired = "feedback.notification_title_body_required"
    static let feedbackNotificationSent = "feedback.notification_sent"

    static let roleValueMember = "role.value.member"
    static let roleValueProducer = "role.value.producer"
    static let roleValueAdmin = "role.value.admin"
    static let newsEmptyState = "news.empty_state"
    static let newsViewAll = "news.view_all"
    static let newsListSubtitle = "news.list.subtitle"
    static let newsRefreshAction = "news.refresh.action"
    static let newsLoading = "news.loading"
    static let newsMetaFormat = "news.meta_format"
    static let newsInactiveBadge = "news.inactive_badge"
    static let newsCreateAction = "news.create.action"
    static let newsEditAction = "news.edit.action"
    static let newsDeleteAction = "news.delete.action"
    static let newsDeleteDialogTitle = "news.delete.dialog.title"
    static let newsDeleteDialogMessage = "news.delete.dialog.message"
    static let newsDeleteActionConfirm = "news.delete.action.confirm"
    static let newsDeleteActionCancel = "news.delete.action.cancel"
    static let newsEditorTitleCreate = "news.editor.title.create"
    static let newsEditorTitleEdit = "news.editor.title.edit"
    static let newsEditorSubtitle = "news.editor.subtitle"
    static let newsFieldTitle = "news.field.title"
    static let newsFieldBody = "news.field.body"
    static let newsFieldURLImage = "news.field.url_image"
    static let newsFieldActive = "news.field.active"
    static let newsSaveActionCreate = "news.save.action.create"
    static let newsSaveActionUpdate = "news.save.action.update"
    static let newsSaveActionSaving = "news.save.action.saving"
    static let notificationsEmptyState = "notifications.empty_state"
    static let notificationsListSubtitle = "notifications.list.subtitle"
    static let notificationsRefreshAction = "notifications.refresh.action"
    static let notificationsLoading = "notifications.loading"
    static let notificationsMetaFormat = "notifications.meta_format"
    static let notificationsCreateAction = "notifications.create.action"
    static let notificationsEditorTitle = "notifications.editor.title"
    static let notificationsEditorSubtitle = "notifications.editor.subtitle"
    static let notificationsFieldTitle = "notifications.field.title"
    static let notificationsFieldBody = "notifications.field.body"
    static let notificationsFieldAudience = "notifications.field.audience"
    static let notificationsSendActionSend = "notifications.send.action.send"
    static let notificationsSendActionSending = "notifications.send.action.sending"
    static let notificationsTargetAll = "notifications.target.all"
    static let notificationsTargetMembers = "notifications.target.members"
    static let notificationsTargetProducers = "notifications.target.producers"
    static let notificationsTargetAdmins = "notifications.target.admins"
    static let notificationsTargetUsers = "notifications.target.users"
    static let profileSharedTitle = "profile.shared.title"
    static let profileSharedSubtitle = "profile.shared.subtitle"
    static let profileSharedFamilyNamesLabel = "profile.shared.family_names.label"
    static let profileSharedPhotoURLLabel = "profile.shared.photo_url.label"
    static let profileSharedAboutLabel = "profile.shared.about.label"
    static let profileSharedPhotoPreview = "profile.shared.photo.preview"
    static let profileSharedHubTitle = "profile.shared.hub.title"
    static let profileSharedHubSubtitle = "profile.shared.hub.subtitle"
    static let profileSharedEditorTitleCreate = "profile.shared.editor.title.create"
    static let profileSharedEditorTitleEdit = "profile.shared.editor.title.edit"
    static let profileSharedEditorSubtitle = "profile.shared.editor.subtitle"
    static let profileSharedActionViewMyProfile = "profile.shared.action.view_my_profile"
    static let profileSharedActionCreate = "profile.shared.action.create"
    static let profileSharedActionEdit = "profile.shared.action.edit"
    static let profileSharedCommunityTitle = "profile.shared.community.title"
    static let profileSharedCommunitySubtitle = "profile.shared.community.subtitle"
    static let profileSharedLoading = "profile.shared.loading"
    static let profileSharedEmpty = "profile.shared.empty"
    static let profileSharedActionSave = "profile.shared.action.save"
    static let profileSharedActionSaving = "profile.shared.action.saving"
    static let profileSharedActionDelete = "profile.shared.action.delete"
    static let profileSharedActionDeleting = "profile.shared.action.deleting"
    static let feedbackSharedProfileContentRequired = "feedback.shared_profile_content_required"
    static let feedbackSharedProfileSaved = "feedback.shared_profile_saved"
    static let feedbackSharedProfileDeleted = "feedback.shared_profile_deleted"
    static let feedbackSharedProfileDeleteFailed = "feedback.shared_profile_delete_failed"
}

func l10n(_ key: String) -> String {
    NSLocalizedString(key, comment: "")
}

func l10n(_ key: String, _ arguments: CVarArg...) -> String {
    String(format: NSLocalizedString(key, comment: ""), locale: Locale.current, arguments: arguments)
}

func localizedUnauthorizedReason(_ reason: UnauthorizedReason) -> String {
    switch reason {
    case .userNotFoundInAuthorizedUsers, .userAccessRestricted:
        return l10n(AccessL10nKey.unauthorized)
    }
}

func localizedRoleValue(_ role: MemberRole) -> String {
    switch role {
    case .member:
        return l10n(AccessL10nKey.roleValueMember)
    case .producer:
        return l10n(AccessL10nKey.roleValueProducer)
    case .admin:
        return l10n(AccessL10nKey.roleValueAdmin)
    }
}
