package com.reguerta.user.presentation.auth

import com.reguerta.user.presentation.root.MemberDraft
import com.reguerta.user.presentation.root.MyOrderFreshnessUiState
import com.reguerta.user.presentation.root.NewsDraft
import com.reguerta.user.presentation.root.NotificationDraft
import com.reguerta.user.presentation.root.ProductDraft
import com.reguerta.user.presentation.root.SessionMode
import com.reguerta.user.presentation.root.SessionUiState
import com.reguerta.user.presentation.root.SharedProfileDraft
import com.reguerta.user.presentation.root.ShiftSwapDraft
import com.reguerta.user.presentation.root.canManageSessionProductCatalog

import com.reguerta.user.domain.access.UnauthorizedReason

internal fun SessionUiState.toSignedOutSessionState(
    showSessionExpiredDialog: Boolean,
): SessionUiState = copy(
    sessionEpoch = sessionEpoch + 1,
    sessionEnvironment = null,
    mode = SessionMode.SignedOut,
    emailErrorRes = null,
    passwordErrorRes = null,
    isAuthenticating = false,
    registerEmailInput = "",
    registerEmailErrorRes = null,
    registerPasswordErrorRes = null,
    registerRepeatPasswordErrorRes = null,
    isRegistering = false,
    recoverEmailInput = "",
    recoverEmailErrorRes = null,
    isRecoveringPassword = false,
    showRecoverSuccessDialog = false,
    showSessionExpiredDialog = showSessionExpiredDialog,
    showUnauthorizedDialog = false,
    memberDraft = MemberDraft(),
    myOrderFreshnessState = MyOrderFreshnessUiState.Idle,
    myOrderFreshnessGeneration = null,
    myOrderFreshnessConsumerReceipt = null,
    latestNews = emptyList(),
    newsFeed = emptyList(),
    newsDraft = NewsDraft(),
    notificationsFeed = emptyList(),
    readNotificationIds = emptySet(),
    notificationDraft = NotificationDraft(),
    productsFeed = emptyList(),
    myOrderProductsFeed = emptyList(),
    myOrderSeasonalCommitmentsFeed = emptyList(),
    productDraft = ProductDraft(),
    editingProductId = null,
    pendingNewProductId = null,
    productEditorRevision = productEditorRevision + 1,
    sharedProfiles = emptyList(),
    sharedProfileDraft = SharedProfileDraft(),
    sharedProfileEditorRevision = sharedProfileEditorRevision + 1,
    sharedProfilesRevision = sharedProfilesRevision + 1,
    shiftsFeed = emptyList(),
    deliveryCalendarOverrides = emptyList(),
    defaultDeliveryDayOfWeek = null,
    shiftSwapRequests = emptyList(),
    dismissedShiftSwapRequestIds = emptySet(),
    acknowledgedShiftSwapRequestIds = emptySet(),
    acknowledgedShiftSwapCreates = emptyMap(),
    shiftSwapDraft = ShiftSwapDraft(),
    nextDeliveryShift = null,
    nextMarketShift = null,
    editingNewsId = null,
    isLoadingNews = false,
    isSavingNews = false,
    isUploadingNewsImage = false,
    isLoadingNotifications = false,
    isSendingNotification = false,
    isPushNotificationPermissionActive = true,
    showPushNotificationPermissionDialog = false,
    isLoadingProducts = false,
    isLoadingMyOrderProducts = false,
    isSavingProduct = false,
    isUploadingProductImage = false,
    isUpdatingProducerCatalogVisibility = false,
    isLoadingSharedProfiles = false,
    isSavingSharedProfile = false,
    isUploadingSharedProfileImage = false,
    isDeletingSharedProfile = false,
    isLoadingShifts = false,
    isLoadingDeliveryCalendar = false,
    isSavingDeliveryCalendar = false,
    isSubmittingShiftPlanningRequest = false,
    isSavingShiftSwapRequest = false,
    isUpdatingShiftSwapRequest = false,
)

internal fun SessionUiState.resetProductEditorUnlessAuthorizedRefreshCanPreserve(
    principalUid: String,
    member: com.reguerta.user.domain.access.Member,
): SessionUiState {
    val currentMode = mode as? SessionMode.Authorized
    val canPreserve = currentMode?.principal?.uid == principalUid &&
        currentMode.member.id == member.id &&
        member.canManageSessionProductCatalog
    if (canPreserve) return this
    return copy(
        productDraft = ProductDraft(),
        editingProductId = null,
        pendingNewProductId = null,
        productEditorRevision = productEditorRevision + 1,
        isSavingProduct = false,
        isUploadingProductImage = false,
        isUpdatingProducerCatalogVisibility = false,
    )
}

internal fun SessionUiState.toUnauthorizedSessionState(
    email: String,
    reason: UnauthorizedReason,
    showUnauthorizedDialog: Boolean,
): SessionUiState = copy(
    sessionEpoch = sessionEpoch + 1,
    sessionEnvironment = null,
    mode = SessionMode.Unauthorized(
        email = email,
        reason = reason,
    ),
    showSessionExpiredDialog = false,
    showUnauthorizedDialog = showUnauthorizedDialog,
    myOrderFreshnessState = MyOrderFreshnessUiState.Idle,
    myOrderFreshnessGeneration = null,
    myOrderFreshnessConsumerReceipt = null,
    latestNews = emptyList(),
    newsFeed = emptyList(),
    newsDraft = NewsDraft(),
    notificationsFeed = emptyList(),
    readNotificationIds = emptySet(),
    notificationDraft = NotificationDraft(),
    productsFeed = emptyList(),
    myOrderProductsFeed = emptyList(),
    myOrderSeasonalCommitmentsFeed = emptyList(),
    productDraft = ProductDraft(),
    editingProductId = null,
    pendingNewProductId = null,
    productEditorRevision = productEditorRevision + 1,
    sharedProfiles = emptyList(),
    sharedProfileDraft = SharedProfileDraft(),
    sharedProfileEditorRevision = sharedProfileEditorRevision + 1,
    sharedProfilesRevision = sharedProfilesRevision + 1,
    shiftsFeed = emptyList(),
    deliveryCalendarOverrides = emptyList(),
    defaultDeliveryDayOfWeek = null,
    shiftSwapRequests = emptyList(),
    dismissedShiftSwapRequestIds = emptySet(),
    acknowledgedShiftSwapRequestIds = emptySet(),
    acknowledgedShiftSwapCreates = emptyMap(),
    shiftSwapDraft = ShiftSwapDraft(),
    nextDeliveryShift = null,
    nextMarketShift = null,
    editingNewsId = null,
    isLoadingNews = false,
    isSavingNews = false,
    isUploadingNewsImage = false,
    isLoadingNotifications = false,
    isSendingNotification = false,
    isPushNotificationPermissionActive = true,
    showPushNotificationPermissionDialog = false,
    isLoadingProducts = false,
    isLoadingMyOrderProducts = false,
    isSavingProduct = false,
    isUploadingProductImage = false,
    isLoadingSharedProfiles = false,
    isSavingSharedProfile = false,
    isUploadingSharedProfileImage = false,
    isDeletingSharedProfile = false,
    isLoadingShifts = false,
    isLoadingDeliveryCalendar = false,
    isSavingDeliveryCalendar = false,
    isSubmittingShiftPlanningRequest = false,
    isSavingShiftSwapRequest = false,
    isUpdatingShiftSwapRequest = false,
)
