import Foundation

extension AccessL10nKey {
    static let shiftSwapRequestScreenTitle = "shift_swap_request.screen.title"
    static let shiftSwapRequestScreenSubtitle = "shift_swap_request.screen.subtitle"
    static let shiftSwapRequestRequestsTitle = "shift_swap_request.requests.title"
    static let shiftSwapRequestRequestsSubtitle = "shift_swap_request.requests.subtitle"
    static let shiftSwapRequestEmpty = "shift_swap_request.empty"
    static let shiftSwapRequestIncoming = "shift_swap_request.incoming"
    static let shiftSwapRequestOutgoing = "shift_swap_request.outgoing"
    static let shiftSwapRequestHistory = "shift_swap_request.history"
    static let shiftSwapRequestReasonLabel = "shift_swap_request.reason.label"
    static let shiftSwapRequestActionSend = "shift_swap_request.action.send"
    static let shiftSwapRequestActionSending = "shift_swap_request.action.sending"
    static let shiftSwapRequestActionBack = "shift_swap_request.action.back"
    static let shiftSwapRequestActionCancel = "shift_swap_request.action.cancel"
    static let shiftSwapRequestActionConfirm = "shift_swap_request.action.confirm"
    static let shiftSwapRequestActionAcknowledge = "shift_swap_request.action.acknowledge"
    static let shiftSwapRequestReasonEmpty = "shift_swap_request.reason.empty"
    static let shiftSwapRequestResponsesTitle = "shift_swap_request.responses.title"
    static let shiftSwapRequestStatusOpen = "shift_swap_request.status.open"
    static let shiftSwapRequestStatusCancelled = "shift_swap_request.status.cancelled"
    static let shiftSwapRequestStatusApplied = "shift_swap_request.status.applied"
    static let shiftSwapNotificationRequestedTitle = "shift_swap_notification.requested.title"
    static let shiftSwapNotificationRequestedBody = "shift_swap_notification.requested.body"
    static let shiftSwapNotificationAppliedTitle = "shift_swap_notification.applied.title"
    static let shiftSwapNotificationAppliedBody = "shift_swap_notification.applied.body"
    static let shiftSwapNotificationResponseAvailableTitle = "shift_swap_notification.response.available.title"
    static let shiftSwapNotificationResponseUnavailableTitle = "shift_swap_notification.response.unavailable.title"
    static let shiftSwapNotificationResponseAvailableBody = "shift_swap_notification.response.available.body"
    static let shiftSwapNotificationResponseUnavailableBody = "shift_swap_notification.response.unavailable.body"
    static let shiftSwapNotificationResponseAvailableBodyWithSource = "shift_swap_notification.response.available.body_with_source"
    static let shiftSwapNotificationResponseUnavailableBodyWithSource = "shift_swap_notification.response.unavailable.body_with_source"
    static let shiftSwapRequestActionAsk = "shift_swap_request.action.ask"
    static let shiftSwapRequestScopeDelivery = "shift_swap_request.scope.delivery"
    static let shiftSwapRequestScopeMarket = "shift_swap_request.scope.market"
    static let shiftSwapRequestActionAcceptShort = "shift_swap_request.action.accept_short"
    static let shiftSwapRequestActionRejectShort = "shift_swap_request.action.reject_short"
    static let shiftSwapRequestFormatShift = "shift_swap_request.format.shift"
    static let shiftSwapRequestFormatBroadcastScope = "shift_swap_request.format.broadcast_scope"
    static let shiftSwapRequestFormatRequestedBy = "shift_swap_request.format.requested_by"
    static let shiftSwapRequestFormatOfferShift = "shift_swap_request.format.offer_shift"
    static let shiftSwapRequestFormatReason = "shift_swap_request.format.reason"
    static let shiftSwapRequestFormatWaitingMany = "shift_swap_request.format.waiting_many"
    static let shiftSwapRequestFormatConfirmBeforeAfter = "shift_swap_request.format.confirm_before_after"
    static let shiftSwapRequestFormatSelected = "shift_swap_request.format.selected"
}
