package com.reguerta.user.presentation.access

import com.reguerta.user.domain.access.UnauthorizedReason

internal fun SessionUiState.toSignedOutSessionState(
    showSessionExpiredDialog: Boolean,
): SessionUiState = copy(
    mode = SessionMode.SignedOut,
    passwordInput = "",
    emailErrorRes = null,
    passwordErrorRes = null,
    isAuthenticating = false,
    registerEmailInput = "",
    registerPasswordInput = "",
    registerRepeatPasswordInput = "",
    registerEmailErrorRes = null,
    registerPasswordErrorRes = null,
    registerRepeatPasswordErrorRes = null,
    isRegistering = false,
    recoverEmailInput = "",
    recoverEmailErrorRes = null,
    isRecoveringPassword = false,
    showRecoverSuccessDialog = false,
    showSessionExpiredDialog = showSessionExpiredDialog,
    showUnauthorizedDialog = false,
    memberDraft = MemberDraft(),
    myOrderFreshnessState = MyOrderFreshnessUiState.Idle,
    latestNews = emptyList(),
    newsFeed = emptyList(),
    newsDraft = NewsDraft(),
    notificationsFeed = emptyList(),
    notificationDraft = NotificationDraft(),
    productsFeed = emptyList(),
    myOrderProductsFeed = emptyList(),
    productDraft = ProductDraft(),
    sharedProfiles = emptyList(),
    sharedProfileDraft = SharedProfileDraft(),
    shiftsFeed = emptyList(),
    nextDeliveryShift = null,
    nextMarketShift = null,
    editingNewsId = null,
    isLoadingNews = false,
    isSavingNews = false,
    isLoadingNotifications = false,
    isSendingNotification = false,
    isLoadingProducts = false,
    isLoadingMyOrderProducts = false,
    isSavingProduct = false,
    isUpdatingProducerCatalogVisibility = false,
    isLoadingSharedProfiles = false,
    isSavingSharedProfile = false,
    isDeletingSharedProfile = false,
    isLoadingShifts = false,
)

internal fun SessionUiState.toUnauthorizedSessionState(
    email: String,
    reason: UnauthorizedReason,
    showUnauthorizedDialog: Boolean,
): SessionUiState = copy(
    mode = SessionMode.Unauthorized(
        email = email,
        reason = reason,
    ),
    showSessionExpiredDialog = false,
    showUnauthorizedDialog = showUnauthorizedDialog,
    myOrderFreshnessState = MyOrderFreshnessUiState.Idle,
    latestNews = emptyList(),
    newsFeed = emptyList(),
    newsDraft = NewsDraft(),
    notificationsFeed = emptyList(),
    notificationDraft = NotificationDraft(),
    productsFeed = emptyList(),
    myOrderProductsFeed = emptyList(),
    productDraft = ProductDraft(),
    sharedProfiles = emptyList(),
    sharedProfileDraft = SharedProfileDraft(),
    shiftsFeed = emptyList(),
    nextDeliveryShift = null,
    nextMarketShift = null,
    editingNewsId = null,
    isLoadingNews = false,
    isSavingNews = false,
    isLoadingNotifications = false,
    isSendingNotification = false,
    isLoadingProducts = false,
    isLoadingMyOrderProducts = false,
    isSavingProduct = false,
    isLoadingSharedProfiles = false,
    isSavingSharedProfile = false,
    isDeletingSharedProfile = false,
    isLoadingShifts = false,
)

internal fun SessionUiState.toUnauthorizedAfterAuthAttemptState(
    email: String,
    reason: UnauthorizedReason,
    showUnauthorizedDialog: Boolean,
    clearRegisterInputs: Boolean,
): SessionUiState = copy(
    isAuthenticating = false,
    isRegistering = false,
    registerEmailInput = if (clearRegisterInputs) "" else registerEmailInput,
    registerPasswordInput = if (clearRegisterInputs) "" else registerPasswordInput,
    registerRepeatPasswordInput = if (clearRegisterInputs) "" else registerRepeatPasswordInput,
    mode = SessionMode.Unauthorized(
        email = email,
        reason = reason,
    ),
    showUnauthorizedDialog = showUnauthorizedDialog,
    myOrderFreshnessState = MyOrderFreshnessUiState.Idle,
    notificationsFeed = emptyList(),
    notificationDraft = NotificationDraft(),
    myOrderProductsFeed = emptyList(),
    isLoadingNotifications = false,
    isSendingNotification = false,
    isLoadingMyOrderProducts = false,
)
